name: ime_pay
description: Flutter plugin for IME Pay.
version: 0.0.2
homepage: https://github.com/bimsina/ime_pay.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.5 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.bimsina.ime_pay
        pluginClass: ImePayPlugin
      ios:
        pluginClass: ImePayPlugin
